/**
 * Settings for connected accounts (Gmail). Declared here rather than
 * generated by `wrangler types`: the secrets are set with `wrangler secret put`
 * and may not exist yet, so the code checks them and says what is missing.
 */
interface GoogleSourceEnv {
  /** OAuth client (Google Cloud → Clients). Secret. */
  GOOGLE_CLIENT_ID?: string;
  /** Secret. */
  GOOGLE_CLIENT_SECRET?: string;
  /** 32 random bytes, base64. Seals refresh tokens at rest. Secret. */
  SOURCE_TOKEN_KEY?: string;
  /** projects/<project>/topics/<topic> that Gmail publishes new-mail alerts to. */
  GMAIL_PUBSUB_TOPIC?: string;
  /** The service account Pub/Sub signs push requests as. */
  PUBSUB_PUSH_SA?: string;
}
interface Env extends GoogleSourceEnv {}
declare namespace Cloudflare {
  interface Env extends GoogleSourceEnv {}
}
